module.exports = [
  {
    className: '_Role',
    fields: {},
    classLevelPermissions: {
      find: {},
      get: {},
      create: {},
      update: {},
      delete: {},
      protectedFields: {},
    },
  },
  {
    className: '_User',
    fields: {},
    classLevelPermissions: {
      find: {},
      get: {},
      create: { '*': true },
      update: {},
      delete: {},
      protectedFields: {},
    },
  },
  {
    className: '_Session',
    fields: {},
    classLevelPermissions: {
      find: {},
      get: {},
      create: {},
      update: {},
      delete: {},
      protectedFields: {},
    },
  },
  {
    className: 'OAuthApplication',
    description: 'Application created by developers to allow access to data',
    fields: {
      name: { type: 'String', required: true },
      description: { type: 'String', required: true },
      owner: { type: 'Pointer', required: true, targetClass: '_User' },
      appleStoreLink: { type: 'String' },
      googleMarketLink: { type: 'String' },
      publicKey: { type: 'String' },
      secretKey: { type: 'String' },
    },
    required: ['name', 'description'],
    additionalProperties: false,
    classLevelPermissions: {
      find: {},
      get: {},
      readUserFields: ['owner'],
      writeUserFields: ['owner'],
      create: { 'role:Developer': true },
      update: { 'role:Administrator': true },
      delete: { 'role:Administrator': true },
      protectedFields: { '*': ['owner'], owner: [], 'role:Administrator': [] },
    },
  },
];
