version: '3.1'
services:
  mongo:
    image: mongo:4
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - connect-mongo-storage:/data/db
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  node:
    image: node:latest
    environment:
      - DEBUG=connect*
    volumes:
      - $PWD:/usr/src
    working_dir: /usr/src
volumes:
  connect-mongo-storage:
