version: '3'

services:
  connect:
    network_mode: host
    image: criconnect/connect:$VERSION_NUMBER
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - .env

  connect-sandbox:
    network_mode: host
    image: criconnect/connect:$VERSION_NUMBER
    command: ['yarn', 'start.sandbox']
    ports:
      - '3001:3001'
    restart: always
    env_file:
      - .env
