module.exports = {
  DEBUG: true,
  PUBLIC_URL: 'http://localhost:3000',
  API_URL: 'http://localhost:3000',
  APP_PORT: '3000',
  // SANDBOX_URL: 'http://localhost:3000',
  // SANDBOX_PORT: '3000',
  PARSE_APP_NAME: 'test',
  PARSE_APP_ID: 'test',
  PARSE_FILE_KEY: 'test',
  PARSE_MASTER_KEY: 'test_masterkey',
  PARSE_READONLY_MASTER_KEY: 'test_masterkey_readonly',
  PARSE_DASHBOARD_MAINTENER_PWD: 'test',
  PARSE_DASHBOARD_ROOT_PWD: 'test',
  PARSE_SANDBOX: false,
  PARSE_SILENT: true,
  MONGO_URI: 'mongodb://test:test@localhost:27017/test',
  AUTH_SECRET: 'test',
  GITHUB_CLIENT_ID: 'test',
  GITHUB_CLIENT_SECRET: 'test',
};
