name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup env variables
        run: cp .env.dist .env
      - name: Install modules
        run: yarn
      - name: Build the react app
        run: yarn build
      - name: Run tests
        run: yarn test
